import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'el';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const defaultLanguage: Language = 'en';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Common translations
    'common.home': 'Home',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.services': 'Services',
    'common.testimonials': 'Testimonials',
    'common.faq': 'FAQ',
    'common.blog': 'Blog',
    'common.pricing': 'Pricing',
    'common.features': 'Features',
    'common.team': 'Team',
    'common.portfolio': 'Portfolio',
    'common.careers': 'Careers',
    'common.terms': 'Terms',
    'common.privacy': 'Privacy',
    'common.settings': 'Settings',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.signup': 'Sign Up',
    'common.dashboard': 'Dashboard',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.view': 'View',
    'common.all': 'All',
    'common.details': 'Details',
    'common.close': 'Close',
    'common.menu': 'Menu',
    'common.language': 'Language',
    'common.selectLanguage': 'Select Language',
    'common.confirm': 'Confirm',
    'common.warning': 'Warning',
    'common.information': 'Information',
    'common.overview': 'Overview',
    'common.statistics': 'Statistics',
    'common.options': 'Options',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.location': 'Location',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.message': 'Message',
    'common.send': 'Send',
    'common.reset': 'Reset',
    'common.password': 'Password',
    'common.address': 'Address',
    'common.city': 'City',
    'common.country': 'Country',
    'common.state': 'State',
    'common.zip': 'Zip Code',
    'common.description': 'Description',
    'common.title': 'Title',
    'common.content': 'Content',
    'common.author': 'Author',
    'common.category': 'Category',
    'common.tags': 'Tags',
    'common.share': 'Share',
    'common.follow': 'Follow',
    'common.subscribe': 'Subscribe',
    'common.unsubscribe': 'Unsubscribe',
    'common.searchPlaceholder': 'Enter keywords...',
    'common.noResults': 'No results found',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.readMore': 'Read More',
    'common.contactUs': 'Contact Us',
    'common.aboutUs': 'About Us',
    'common.ourServices': 'Our Services',
    'common.ourTeam': 'Our Team',
    'common.ourPortfolio': 'Our Portfolio',
    'common.ourClients': 'Our Clients',
    'common.ourTestimonials': 'Our Testimonials',
    'common.ourBlog': 'Our Blog',
    'common.ourFaq': 'Our FAQ',
    'common.ourPricing': 'Our Pricing',
    'common.ourFeatures': 'Our Features',
    'common.ourCareers': 'Our Careers',
    'common.ourTerms': 'Our Terms',
    'common.ourPrivacy': 'Our Privacy',
    'common.ourSettings': 'Our Settings',
    'common.ourLogout': 'Our Logout',
    'common.ourLogin': 'Our Login',
    'common.ourSignup': 'Our Sign Up',
    'common.ourDashboard': 'Our Dashboard',
    'common.ourSearch': 'Our Search',
    'common.ourLoading': 'Our Loading...',
    'common.ourError': 'Our Error',
    'common.ourSuccess': 'Our Success',
    'common.ourEdit': 'Our Edit',
    'common.ourDelete': 'Our Delete',
    'common.ourAdd': 'Our Add',
    'common.ourSave': 'Our Save',
    'common.ourCancel': 'Our Cancel',
    'common.ourBack': 'Our Back',
    'common.ourNext': 'Our Next',
    'common.ourPrevious': 'Our Previous',
    'common.ourSubmit': 'Our Submit',
    'common.ourUpdate': 'Our Update',
    'common.ourCreate': 'Our Create',
    'common.ourView': 'Our View',
    'common.ourAll': 'Our All',
    'common.ourDetails': 'Our Details',
    'common.ourClose': 'Our Close',
    'common.ourMenu': 'Our Menu',
    'common.ourLanguage': 'Our Language',
    'common.ourSelectLanguage': 'Our Select Language',
    'common.ourConfirm': 'Our Confirm',
    'common.ourWarning': 'Our Warning',
    'common.ourInformation': 'Our Information',
    'common.ourOverview': 'Our Overview',
    'common.ourStatistics': 'Our Statistics',
    'common.ourOptions': 'Our Options',
    'common.ourActions': 'Our Actions',
    'common.ourDate': 'Our Date',
    'common.ourTime': 'Our Time',
    'common.ourLocation': 'Our Location',
    'common.ourName': 'Our Name',
    'common.ourEmail': 'Our Email',
    'common.ourPhone': 'Our Phone',
    'common.ourMessage': 'Our Message',
    'common.ourSend': 'Our Send',
    'common.ourReset': 'Our Reset',
    'common.ourPassword': 'Our Password',
    'common.ourAddress': 'Our Address',
    'common.ourCity': 'Our City',
    'common.ourCountry': 'Our Country',
    'common.ourState': 'Our State',
    'common.ourZip': 'Our Zip Code',
    'common.ourDescription': 'Our Description',
    'common.ourTitle': 'Our Title',
    'common.ourContent': 'Our Content',
    'common.ourAuthor': 'Our Author',
    'common.ourCategory': 'Our Category',
    'common.ourTags': 'Our Tags',
    'common.ourShare': 'Our Share',
    'common.ourFollow': 'Our Follow',
    'common.ourSubscribe': 'Our Subscribe',
    'common.ourUnsubscribe': 'Our Unsubscribe',
    'common.ourSearchPlaceholder': 'Enter keywords...',
    'common.ourNoResults': 'No results found',
    'common.ourLearnMore': 'Our Learn More',
    'common.ourGetStarted': 'Our Get Started',
    'common.ourReadMore': 'Our Read More',
    'common.ourContactUs': 'Our Contact Us',
    'common.ourAboutUs': 'Our About Us',
    'common.ourServices': 'Our Services',
    'common.ourTeam': 'Our Team',
    'common.ourPortfolio': 'Our Portfolio',
    'common.ourClients': 'Our Clients',
    'common.ourTestimonials': 'Our Testimonials',
    'common.ourBlog': 'Our Blog',
    'common.ourFaq': 'Our FAQ',
    'common.ourPricing': 'Our Pricing',
    'common.ourFeatures': 'Our Features',
    'common.ourCareers': 'Our Careers',
    'common.ourTerms': 'Our Terms',
    'common.ourPrivacy': 'Our Privacy',
    'common.ourSettings': 'Our Settings',
    'language.en': 'English',
    'language.el': 'Greek',

    // Account
    'account.businessName': 'Business Name',

    // Contact
    'contact.phone': 'Phone Number',

    // Auth
    'auth.welcome': 'Welcome to Repute',
    'auth.loginTitle': 'Login to your account',
    'auth.signupTitle': 'Create your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.loggedOut': 'Logged out',
    'auth.loggedOutDesc': 'You have been successfully logged out',
    'auth.errorLoggingOut': 'Error logging out',
    'auth.logIn': 'Log in',
    'auth.signUp': 'Sign up',
    'auth.verificationEmailSent': 'Verification email sent',
    'auth.verificationEmailDesc': 'Please check your inbox and verify your email before logging in',
    'auth.emailVerificationRequired': 'Email verification required',
    'auth.emailVerificationDesc': 'You need to verify your email before logging in',
  },
  el: {
    // Common translations in Greek
    'common.home': 'Αρχική',
    'common.about': 'Σχετικά',
    'common.contact': 'Επικοινωνία',
    'common.services': 'Υπηρεσίες',
    'common.testimonials': 'Μαρτυρίες',
    'common.faq': 'Συχνές Ερωτήσεις',
    'common.blog': 'Blog',
    'common.pricing': 'Τιμολόγηση',
    'common.features': 'Χαρακτηριστικά',
    'common.team': 'Ομάδα',
    'common.portfolio': 'Portfolio',
    'common.careers': 'Καριέρες',
    'common.terms': 'Όροι',
    'common.privacy': 'Ιδιωτικότητα',
    'common.settings': 'Ρυθμίσεις',
    'common.logout': 'Αποσύνδεση',
    'common.login': 'Σύνδεση',
    'common.signup': 'Εγγραφή',
    'common.dashboard': 'Πίνακας Ελέγχου',
    'common.search': 'Αναζήτηση',
    'common.loading': 'Φόρτωση...',
    'common.error': 'Σφάλμα',
    'common.success': 'Επιτυχία',
    'common.edit': 'Επεξεργασία',
    'common.delete': 'Διαγραφή',
    'common.add': 'Προσθήκη',
    'common.save': 'Αποθήκευση',
    'common.cancel': 'Ακύρωση',
    'common.back': 'Πίσω',
    'common.next': 'Επόμενο',
    'common.previous': 'Προηγούμενο',
    'common.submit': 'Υποβολή',
    'common.update': 'Ενημέρωση',
    'common.create': 'Δημιουργία',
    'common.view': 'Προβολή',
    'common.all': 'Όλα',
    'common.details': 'Λεπτομέρειες',
    'common.close': 'Κλείσιμο',
    'common.menu': 'Μενού',
    'common.language': 'Γλώσσα',
    'common.selectLanguage': 'Επιλογή Γλώσσας',
    'common.confirm': 'Επιβεβαίωση',
    'common.warning': 'Προειδοποίηση',
    'common.information': 'Πληροφορίες',
    'common.overview': 'Επισκόπηση',
    'common.statistics': 'Στατιστικά',
    'common.options': 'Επιλογές',
    'common.actions': 'Ενέργειες',
    'common.date': 'Ημερομηνία',
    'common.time': 'Ώρα',
    'common.location': 'Τοποθεσία',
    'common.name': 'Όνομα',
    'common.email': 'Email',
    'common.phone': 'Τηλέφωνο',
    'common.message': 'Μήνυμα',
    'common.send': 'Αποστολή',
    'common.reset': 'Επαναφορά',
    'common.password': 'Κωδικός',
    'common.address': 'Διεύθυνση',
    'common.city': 'Πόλη',
    'common.country': 'Χώρα',
    'common.state': 'Πολιτεία',
    'common.zip': 'ΤΚ',
    'common.description': 'Περιγραφή',
    'common.title': 'Τίτλος',
    'common.content': 'Περιεχόμενο',
    'common.author': 'Συγγραφέας',
    'common.category': 'Κατηγορία',
    'common.tags': 'Tags',
    'common.share': 'Κοινή χρήση',
    'common.follow': 'Ακολούθησε',
    'common.subscribe': 'Εγγραφή',
    'common.unsubscribe': 'Διαγραφή',
    'common.searchPlaceholder': 'Εισάγετε λέξεις-κλειδιά...',
    'common.noResults': 'Δεν βρέθηκαν αποτελέσματα',
    'common.learnMore': 'Μάθετε περισσότερα',
    'common.getStarted': 'Ξεκινήστε',
    'common.readMore': 'Διαβάστε περισσότερα',
    'common.contactUs': 'Επικοινωνήστε μαζί μας',
    'common.aboutUs': 'Σχετικά με εμάς',
    'common.ourServices': 'Οι υπηρεσίες μας',
    'common.ourTeam': 'Η ομάδα μας',
    'common.ourPortfolio': 'Το portfolio μας',
    'common.ourClients': 'Οι πελάτες μας',
    'common.ourTestimonials': 'Οι μαρτυρίες μας',
    'common.ourBlog': 'Το blog μας',
    'common.ourFaq': 'Οι συχνές ερωτήσεις μας',
    'common.ourPricing': 'Η τιμολόγησή μας',
    'common.ourFeatures': 'Τα χαρακτηριστικά μας',
    'common.ourCareers': 'Οι καριέρες μας',
    'common.ourTerms': 'Οι όροι μας',
    'common.ourPrivacy': 'Η ιδιωτικότητά μας',
    'common.ourSettings': 'Οι ρυθμίσεις μας',
    'common.ourLogout': 'Η αποσύνδεσή μας',
    'common.ourLogin': 'Η σύνδεσή μας',
    'common.ourSignup': 'Η εγγραφή μας',
    'common.ourDashboard': 'Ο πίνακας ελέγχου μας',
    'common.ourSearch': 'Η αναζήτησή μας',
    'common.ourLoading': 'Η φόρτωσή μας...',
    'common.ourError': 'Το σφάλμα μας',
    'common.ourSuccess': 'Η επιτυχία μας',
    'common.ourEdit': 'Η επεξεργασία μας',
    'common.ourDelete': 'Η διαγραφή μας',
    'common.ourAdd': 'Η προσθήκη μας',
    'common.ourSave': 'Η αποθήκευσή μας',
    'common.ourCancel': 'Η ακύρωσή μας',
    'common.ourBack': 'Η επιστροφή μας',
    'common.ourNext': 'Το επόμενό μας',
    'common.ourPrevious': 'Το προηγούμενό μας',
    'common.ourSubmit': 'Η υποβολή μας',
    'common.ourUpdate': 'Η ενημέρωσή μας',
    'common.ourCreate': 'Η δημιουργία μας',
    'common.ourView': 'Η προβολή μας',
    'common.ourAll': 'Όλα μας',
    'common.ourDetails': 'Οι λεπτομέρειές μας',
    'common.ourClose': 'Το κλείσιμό μας',
    'common.ourMenu': 'Το μενού μας',
    'common.ourLanguage': 'Η γλώσσα μας',
    'common.ourSelectLanguage': 'Η επιλογή γλώσσας μας',
    'common.ourConfirm': 'Η επιβεβαίωσή μας',
    'common.ourWarning': 'Η προειδοποίησή μας',
    'common.ourInformation': 'Οι πληροφορίες μας',
    'common.ourOverview': 'Η επισκόπησή μας',
    'common.ourStatistics': 'Τα στατιστικά μας',
    'common.ourOptions': 'Οι επιλογές μας',
    'common.ourActions': 'Οι ενέργειές μας',
    'common.ourDate': 'Η ημερομηνία μας',
    'common.ourTime': 'Η ώρα μας',
    'common.ourLocation': 'Η τοποθεσία μας',
    'common.ourName': 'Το όνομά μας',
    'common.ourEmail': 'Το email μας',
    'common.ourPhone': 'Το τηλέφωνό μας',
    'common.ourMessage': 'Το μήνυμά μας',
    'common.ourSend': 'Η αποστολή μας',
    'common.ourReset': 'Η επαναφορά μας',
    'common.ourPassword': 'Ο κωδικός μας',
    'common.ourAddress': 'Η διεύθυνσή μας',
    'common.ourCity': 'Η πόλη μας',
    'common.ourCountry': 'Η χώρα μας',
    'common.ourState': 'Η πολιτεία μας',
    'common.ourZip': 'Ο ΤΚ μας',
    'common.ourDescription': 'Η περιγραφή μας',
    'common.ourTitle': 'Ο τίτλος μας',
    'common.ourContent': 'Το περιεχόμενό μας',
    'common.ourAuthor': 'Ο συγγραφέας μας',
    'common.ourCategory': 'Η κατηγορία μας',
    'common.ourTags': 'Τα tags μας',
    'common.ourShare': 'Η κοινή χρήση μας',
    'common.ourFollow': 'Η παρακολούθησή μας',
    'common.ourSubscribe': 'Η εγγραφή μας',
    'common.ourUnsubscribe': 'Η διαγραφή μας',
    'common.ourSearchPlaceholder': 'Εισάγετε λέξεις-κλειδιά...',
    'common.ourNoResults': 'Δεν βρέθηκαν αποτελέσματα',
    'common.ourLearnMore': 'Μάθετε περισσότερα',
    'common.ourGetStarted': 'Ξεκινήστε',
    'common.ourReadMore': 'Διαβάστε περισσότερα',
    'common.ourContactUs': 'Επικοινωνήστε μαζί μας',
    'common.ourAboutUs': 'Σχετικά με εμάς',
    'common.ourServices': 'Οι υπηρεσίες μας',
    'common.ourTeam': 'Η ομάδα μας',
    'common.ourPortfolio': 'Το portfolio μας',
    'common.ourClients': 'Οι πελάτες μας',
    'common.ourTestimonials': 'Οι μαρτυρίες μας',
    'common.ourBlog': 'Το blog μας',
    'common.ourFaq': 'Οι συχνές ερωτήσεις μας',
    'common.ourPricing': 'Η τιμολόγησή μας',
    'common.ourFeatures': 'Τα χαρακτηριστικά μας',
    'common.ourCareers': 'Οι καριέρες μας',
    'common.ourTerms': 'Οι όροι μας',
    'common.ourPrivacy': 'Η ιδιωτικότητά μας',
    'common.ourSettings': 'Οι ρυθμίσεις μας',
    'language.en': 'Αγγλικά',
    'language.el': 'Ελληνικά',

    // Account
    'account.businessName': 'Όνομα Επιχείρησης',

    // Contact
    'contact.phone': 'Αριθμός Τηλεφώνου',

    // Auth
    'auth.welcome': 'Καλώς ήρθατε στο Repute',
    'auth.loginTitle': 'Σύνδεση στο λογαριασμό σας',
    'auth.signupTitle': 'Δημιουργία λογαριασμού',
    'auth.email': 'Email',
    'auth.password': 'Κωδικός',
    'auth.forgotPassword': 'Ξεχάσατε τον κωδικό;',
    'auth.noAccount': 'Δεν έχετε λογαριασμό;',
    'auth.hasAccount': 'Έχετε ήδη λογαριασμό;',
    'auth.loggedOut': 'Αποσυνδεθήκατε',
    'auth.loggedOutDesc': 'Έχετε αποσυνδεθεί επιτυχώς',
    'auth.errorLoggingOut': 'Σφάλμα αποσύνδεσης',
    'auth.logIn': 'Σύνδεση',
    'auth.signUp': 'Εγγραφή',
    'auth.verificationEmailSent': 'Απεστάλη email επαλήθευσης',
    'auth.verificationEmailDesc': 'Παρακαλώ ελέγξτε τα εισερχόμενά σας και επιβεβαιώστε το email σας πριν συνδεθείτε',
    'auth.emailVerificationRequired': 'Απαιτείται επαλήθευση email',
    'auth.emailVerificationDesc': 'Πρέπει να επαληθεύσετε το email σας πριν συνδεθείτε',
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(defaultLanguage);

  useEffect(() => {
    const storedLanguage = localStorage.getItem('language') as Language;
    if (storedLanguage && (storedLanguage === 'en' || storedLanguage === 'el')) {
      setLanguage(storedLanguage);
    } else {
      localStorage.setItem('language', defaultLanguage);
      setLanguage(defaultLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage: (lang: Language) => {
      setLanguage(lang);
    },
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
